### PR TITLE
PAE-498.2 - Update footer links

### PR DESCRIPTION
**Pull request by luismorenolopera**
Description
---------------
Update the footer links.

**ticket:** [PAE-498](https://pearsonadvance.atlassian.net/browse/PAE-498)

### CODE REVIEW

**Review by ivanvgh — APPROVED** [review]
LGTM

**Comment by Squirrel18** [comment]
Is there a way to keep or add the MKTG_URL_OVERRIDES functionality? That functionality allows us to overwrite these links without code changes. @luismorenolopera

**Comment by luismorenolopera** [comment]
> Is there a way to keep or add the MKTG_URL_OVERRIDES functionality? That functionality allows us to overwrite these links without code changes. @luismorenolopera

Yes, we can use MKTG_URL_PRIVACY and MKTG_URL_TOS, are in the context of the footer

**Comment by Squirrel18** [comment]
> > Is there a way to keep or add the MKTG_URL_OVERRIDES functionality? That functionality allows us to overwrite these links without code changes. @luismorenolopera
> 
> Yes, we can use MKTG_URL_PRIVACY and MKTG_URL_TOS, are in the context of the footer

Where do MKTG_URL_PRIVACY and MKTG_URL_TOS come from? @luismorenolopera

**Comment by luismorenolopera** [comment]
> > > Is there a way to keep or add the MKTG_URL_OVERRIDES functionality? That functionality allows us to overwrite these links without code changes. @luismorenolopera
> > 
> > 
> > Yes, we can use MKTG_URL_PRIVACY and MKTG_URL_TOS, are in the context of the footer
> 
> Where do MKTG_URL_PRIVACY and MKTG_URL_TOS come from? @luismorenolopera

I discovered this with $ {context.keys ()} but I do not find any incidence of this variable @Squirrel18

**Comment by Squirrel18** [comment]
Ok, if those links can be configured through the Django admin, that's fine.

**Review by Squirrel18 — APPROVED** [review]

**Comment by luismorenolopera** [comment]
> Ok, if those links can be configured through the Django admin, that's fine.

It is configured using MKTG_URL_OVERRIDES, so we will not notice the difference with the other sites

**Pull request merged**
